// Application-wide constants

export const ROLES = {
  DONOR: 'DONOR',
  RECIPIENT: 'RECIPIENT',
  VOLUNTEER: 'VOLUNTEER',
  NGO: 'NGO',
  ADMIN: 'ADMIN',
};

export const DONATION_CATEGORIES = {
  EDUCATION: 'EDUCATION',
  HEALTHCARE: 'HEALTHCARE',
  FOOD: 'FOOD',
  SHELTER: 'SHELTER',
  DISASTER_RELIEF: 'DISASTER_RELIEF',
  ORPHAN_CARE: 'ORPHAN_CARE',
  CLEAN_WATER: 'CLEAN_WATER',
  CLOTHING: 'CLOTHING',
  LIVELIHOOD: 'LIVELIHOOD',
  OTHER: 'OTHER',
};

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
};

export const DONATION_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const VOLUNTEER_EVENT_STATUS = {
  UPCOMING: 'UPCOMING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_METHODS = {
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  MOBILE_MONEY: 'MOBILE_MONEY',
  CRYPTO: 'CRYPTO',
};

export const NOTIFICATION_TYPES = {
  DONATION: 'DONATION',
  CAMPAIGN: 'CAMPAIGN',
  VOLUNTEER: 'VOLUNTEER',
  SYSTEM: 'SYSTEM',
  EMERGENCY: 'EMERGENCY',
};

export const URGENCY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const CURRENCY = 'USD';

export const ITEMS_PER_PAGE = 12;

export const MAP_DEFAULT_CENTER = {
  lat: 20.5937,
  lng: 78.9629,
};

export const DATE_FORMAT = 'MMM DD, YYYY';
export const TIME_FORMAT = 'hh:mm A';
export const DATETIME_FORMAT = 'MMM DD, YYYY hh:mm A';
