import { ROLES, DONATION_CATEGORIES, REQUEST_STATUS, DONATION_STATUS, VERIFICATION_STATUS, URGENCY_LEVELS } from './constants';

// Mock Users
export const mockUsers = [
  {
    id: 'user-1',
    email: 'donor@example.com',
    name: 'John Donor',
    role: ROLES.DONOR,
    avatar: null,
    phone: '+1234567890',
    location: 'New York, USA',
    verified: true,
    joinedDate: '2024-01-15',
    bio: 'Passionate about helping communities in need.',
  },
  {
    id: 'user-2',
    email: 'recipient@example.com',
    name: 'Sarah Recipient',
    role: ROLES.RECIPIENT,
    avatar: null,
    phone: '+1234567891',
    location: 'California, USA',
    verified: true,
    joinedDate: '2024-02-20',
    bio: 'Running a community education program.',
  },
  {
    id: 'user-3',
    email: 'volunteer@example.com',
    name: 'Mike Volunteer',
    role: ROLES.VOLUNTEER,
    avatar: null,
    phone: '+1234567892',
    location: 'Texas, USA',
    verified: true,
    joinedDate: '2024-03-10',
    bio: 'Dedicated to community service.',
  },
  {
    id: 'user-4',
    email: 'ngo@example.com',
    name: 'Hope Foundation',
    role: ROLES.NGO,
    avatar: null,
    phone: '+1234567893',
    location: 'Washington, USA',
    verified: true,
    joinedDate: '2023-12-01',
    bio: 'Non-profit organization focused on education and healthcare.',
    registrationNumber: 'NGO-12345',
  },

];

// Mock Donation Requests
export const mockRequests = [
  {
    id: 'req-1',
    title: 'School Supplies for 100 Children',
    description: 'We need basic school supplies including notebooks, pens, pencils, and backpacks for 100 underprivileged children in our community. Your support will help these children start their education journey.',
    category: DONATION_CATEGORIES.EDUCATION,
    urgency: URGENCY_LEVELS.HIGH,
    targetAmount: 5000,
    currentAmount: 3200,
    status: REQUEST_STATUS.ACTIVE,
    createdBy: 'user-2',
    createdByName: 'Sarah Recipient',
    location: 'California, USA',
    createdAt: '2024-11-01T10:00:00Z',
    deadline: '2024-12-31T23:59:59Z',
    images: [],
    beneficiaryCount: 100,
    tags: ['education', 'children', 'school'],
    donorCount: 24,
  },
  {
    id: 'req-2',
    title: 'Emergency Medical Aid for Rural Clinic',
    description: 'Our rural clinic urgently needs medical supplies and equipment to serve 500+ families. We need medicines, first aid kits, and basic medical equipment.',
    category: DONATION_CATEGORIES.HEALTHCARE,
    urgency: URGENCY_LEVELS.CRITICAL,
    targetAmount: 10000,
    currentAmount: 7500,
    status: REQUEST_STATUS.ACTIVE,
    createdBy: 'user-4',
    createdByName: 'Hope Foundation',
    location: 'Rural Texas, USA',
    createdAt: '2024-11-10T08:00:00Z',
    deadline: '2024-12-20T23:59:59Z',
    images: [],
    beneficiaryCount: 500,
    tags: ['healthcare', 'emergency', 'medical'],
    donorCount: 45,
  },
  {
    id: 'req-3',
    title: 'Clean Water Project for Village',
    description: 'Help us install a clean water system for a village of 300 people. This will provide access to safe drinking water and improve health conditions.',
    category: DONATION_CATEGORIES.CLEAN_WATER,
    urgency: URGENCY_LEVELS.HIGH,
    targetAmount: 15000,
    currentAmount: 4500,
    status: REQUEST_STATUS.ACTIVE,
    createdBy: 'user-4',
    createdByName: 'Hope Foundation',
    location: 'Arizona, USA',
    createdAt: '2024-10-15T10:00:00Z',
    deadline: '2025-01-31T23:59:59Z',
    images: [],
    beneficiaryCount: 300,
    tags: ['water', 'infrastructure', 'health'],
    donorCount: 18,
  },
  {
    id: 'req-4',
    title: 'Food Bank for Homeless Shelter',
    description: 'Monthly food supplies needed for homeless shelter serving 50 people daily. Your donation will provide nutritious meals.',
    category: DONATION_CATEGORIES.FOOD,
    urgency: URGENCY_LEVELS.MEDIUM,
    targetAmount: 3000,
    currentAmount: 2100,
    status: REQUEST_STATUS.ACTIVE,
    createdBy: 'user-2',
    createdByName: 'Sarah Recipient',
    location: 'New York, USA',
    createdAt: '2024-11-15T12:00:00Z',
    deadline: '2024-12-15T23:59:59Z',
    images: [],
    beneficiaryCount: 50,
    tags: ['food', 'homeless', 'shelter'],
    donorCount: 32,
  },
  {
    id: 'req-5',
    title: 'Disaster Relief - Flood Victims',
    description: 'Urgent relief needed for families affected by recent floods. Need food, water, clothing, and temporary shelter materials.',
    category: DONATION_CATEGORIES.DISASTER_RELIEF,
    urgency: URGENCY_LEVELS.CRITICAL,
    targetAmount: 20000,
    currentAmount: 12000,
    status: REQUEST_STATUS.ACTIVE,
    createdBy: 'user-4',
    createdByName: 'Hope Foundation',
    location: 'Florida, USA',
    createdAt: '2024-11-20T06:00:00Z',
    deadline: '2024-12-10T23:59:59Z',
    images: [],
    beneficiaryCount: 200,
    tags: ['disaster', 'emergency', 'relief'],
    donorCount: 67,
  },
];

// Mock Donations
export const mockDonations = [
  {
    id: 'don-1',
    donorId: 'user-1',
    donorName: 'John Donor',
    requestId: 'req-1',
    requestTitle: 'School Supplies for 100 Children',
    amount: 500,
    status: DONATION_STATUS.COMPLETED,
    paymentMethod: 'card',
    transactionId: 'TXN-2024-001',
    message: 'Happy to help! Education is the key to a better future.',
    anonymous: false,
    createdAt: '2024-11-15T14:30:00Z',
    completedAt: '2024-11-15T14:31:00Z',
  },
  {
    id: 'don-2',
    donorId: 'user-1',
    donorName: 'John Donor',
    requestId: 'req-2',
    requestTitle: 'Emergency Medical Aid for Rural Clinic',
    amount: 1000,
    status: DONATION_STATUS.COMPLETED,
    paymentMethod: 'bank_transfer',
    transactionId: 'TXN-2024-002',
    message: 'Healthcare is a basic right.',
    anonymous: false,
    createdAt: '2024-11-18T10:00:00Z',
    completedAt: '2024-11-18T10:05:00Z',
  },
  {
    id: 'don-3',
    donorId: 'user-1',
    donorName: 'John Donor',
    requestId: 'req-4',
    requestTitle: 'Food Bank for Homeless Shelter',
    amount: 250,
    status: DONATION_STATUS.COMPLETED,
    paymentMethod: 'card',
    transactionId: 'TXN-2024-003',
    message: null,
    anonymous: true,
    createdAt: '2024-11-20T16:45:00Z',
    completedAt: '2024-11-20T16:46:00Z',
  },
];



// Mock Notifications
export const mockNotifications = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'donation_received',
    title: 'Donation Successful',
    message: 'Your donation of $500 to "School Supplies for 100 Children" was successful.',
    read: false,
    createdAt: '2024-11-15T14:31:00Z',
    link: '/donor/donation-history',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'campaign_update',
    title: 'Campaign Update',
    message: 'The campaign "Winter Relief Campaign 2024" has reached 60% of its goal!',
    read: false,
    createdAt: '2024-11-18T10:00:00Z',
    link: '/donor/browse-requests',
  },
  {
    id: 'notif-3',
    userId: 'user-2',
    type: 'request_approved',
    title: 'Request Approved',
    message: 'Your request "School Supplies for 100 Children" has been approved and is now live.',
    read: true,
    createdAt: '2024-11-01T12:00:00Z',
    link: '/recipient/manage-requests',
  },
];

// Mock Analytics Data
export const mockAnalytics = {
  totalDonations: 145680,
  totalDonors: 1245,
  activeRequests: 87,
  completedRequests: 234,
  totalBeneficiaries: 12450,
  monthlyDonations: [
    { month: 'Jan', amount: 12000 },
    { month: 'Feb', amount: 15000 },
    { month: 'Mar', amount: 18000 },
    { month: 'Apr', amount: 14000 },
    { month: 'May', amount: 16000 },
    { month: 'Jun', amount: 19000 },
    { month: 'Jul', amount: 22000 },
    { month: 'Aug', amount: 20000 },
    { month: 'Sep', amount: 24000 },
    { month: 'Oct', amount: 26000 },
    { month: 'Nov', amount: 28000 },
    { month: 'Dec', amount: 31680 },
  ],
  categoryDistribution: [
    { category: 'Education', value: 35, amount: 50988 },
    { category: 'Healthcare', value: 25, amount: 36420 },
    { category: 'Food', value: 20, amount: 29136 },
    { category: 'Shelter', value: 10, amount: 14568 },
    { category: 'Other', value: 10, amount: 14568 },
  ],
  recentActivity: [
    { type: 'donation', user: 'John D.', amount: 500, time: '2 hours ago' },
    { type: 'request', user: 'Sarah R.', title: 'School Supplies', time: '5 hours ago' },
    { type: 'verification', user: 'Hope Foundation', status: 'approved', time: '1 day ago' },
  ],
};

// Mock Verification Requests (Admin)
export const mockVerificationRequests = [
  {
    id: 'verify-1',
    userId: 'user-6',
    userName: 'New NGO Organization',
    email: 'newngo@example.com',
    role: ROLES.NGO,
    status: VERIFICATION_STATUS.PENDING,
    documents: ['registration.pdf', 'tax-exempt.pdf'],
    submittedAt: '2024-11-20T10:00:00Z',
    registrationNumber: 'NGO-54321',
    address: '123 Main St, City, State',
    phone: '+1234567899',
  },
  {
    id: 'verify-2',
    userId: 'user-7',
    userName: 'Community Leader',
    email: 'leader@example.com',
    role: ROLES.RECIPIENT,
    status: VERIFICATION_STATUS.PENDING,
    documents: ['id-proof.pdf', 'address-proof.pdf'],
    submittedAt: '2024-11-22T14:30:00Z',
    address: '456 Oak Ave, Town, State',
    phone: '+1234567898',
  },
];

export default {
  mockUsers,
  mockRequests,
  mockDonations,
  mockNotifications,
  mockAnalytics,
  mockVerificationRequests,
};
