// Dummy Data for Admin Panel Development
// Mock data for users, donations, requests, campaigns

import {
  ROLES,
  REQUEST_STATUS,
  CAMPAIGN_STATUS,
  TRANSACTION_STATUS,
  VERIFICATION_STATUS,
  URGENCY_LEVELS,
} from './constants';

// =============================================================================
// MOCK USERS
// =============================================================================

export const mockUsers = [
  {
    id: 'user-1',
    name: 'John Donor',
    email: 'john@example.com',
    role: ROLES.DONOR,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    phone: '+1234567890',
    location: 'New York, USA',
    joinedDate: '2024-01-15',
    totalDonations: 5250,
    donationCount: 12,
    isBlocked: false,
    isSuspended: false,
  },
  {
    id: 'user-2',
    name: 'Hope Foundation',
    email: 'info@hopefoundation.org',
    role: ROLES.NGO,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    phone: '+1234567891',
    location: 'Washington, USA',
    joinedDate: '2023-12-01',
    registrationNumber: 'NGO-12345',
    totalRaised: 145000,
    campaignCount: 8,
    isBlocked: false,
    isSuspended: false,
  },
  {
    id: 'user-3',
    name: 'Mike Volunteer',
    email: 'mike@example.com',
    role: ROLES.VOLUNTEER,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    phone: '+1234567892',
    location: 'Texas, USA',
    joinedDate: '2024-03-10',
    hoursLogged: 120,
    eventsAttended: 15,
    isBlocked: false,
    isSuspended: false,
  },
  {
    id: 'user-4',
    name: 'Admin User',
    email: 'admin@barakahaid.com',
    role: ROLES.ADMIN,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    phone: '+1234567893',
    location: 'Global',
    joinedDate: '2023-10-01',
    isBlocked: false,
    isSuspended: false,
  },
  {
    id: 'user-5',
    name: 'New NGO Org',
    email: 'contact@newngo.org',
    role: ROLES.NGO,
    verificationStatus: VERIFICATION_STATUS.PENDING,
    phone: '+1234567894',
    location: 'California, USA',
    joinedDate: '2024-11-20',
    registrationNumber: 'NGO-67890',
    totalRaised: 0,
    campaignCount: 0,
    isBlocked: false,
    isSuspended: false,
  },
  {
    id: 'user-6',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    role: ROLES.DONOR,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    phone: '+1234567895',
    location: 'London, UK',
    joinedDate: '2024-02-20',
    totalDonations: 3200,
    donationCount: 8,
    isBlocked: false,
    isSuspended: false,
  },
  {
    id: 'user-7',
    name: 'Blocked User',
    email: 'blocked@example.com',
    role: ROLES.DONOR,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    phone: '+1234567896',
    location: 'Miami, USA',
    joinedDate: '2024-01-05',
    totalDonations: 100,
    donationCount: 1,
    isBlocked: true,
    isSuspended: false,
  },
];

// =============================================================================
// MOCK DONATIONS
// =============================================================================

export const mockDonations = [
  {
    id: 'don-1',
    donor: { id: 'user-1', name: 'John Donor', email: 'john@example.com' },
    campaign: { id: 'camp-1', title: 'Winter Relief Campaign 2024' },
    amount: 500,
    status: TRANSACTION_STATUS.COMPLETED,
    paymentGateway: 'CARD',
    transactionId: 'TXN-2024-001',
    createdAt: '2024-11-15T14:30:00Z',
  },
  {
    id: 'don-2',
    donor: { id: 'user-1', name: 'John Donor', email: 'john@example.com' },
    campaign: { id: 'camp-2', title: 'Emergency Flood Relief' },
    amount: 1000,
    status: TRANSACTION_STATUS.COMPLETED,
    paymentGateway: 'JAZZCASH',
    transactionId: 'TXN-2024-002',
    createdAt: '2024-11-18T10:00:00Z',
  },
  {
    id: 'don-3',
    donor: { id: 'user-6', name: 'Sarah Johnson', email: 'sarah@example.com' },
    campaign: { id: 'camp-1', title: 'Winter Relief Campaign 2024' },
    amount: 250,
    status: TRANSACTION_STATUS.PENDING,
    paymentGateway: 'EASYPAISA',
    transactionId: 'TXN-2024-003',
    createdAt: '2024-11-20T16:45:00Z',
  },
  {
    id: 'don-4',
    donor: { id: null, name: 'Anonymous', email: null },
    campaign: { id: 'camp-2', title: 'Emergency Flood Relief' },
    amount: 150,
    status: TRANSACTION_STATUS.COMPLETED,
    paymentGateway: 'CARD',
    transactionId: 'TXN-2024-004',
    createdAt: '2024-11-22T09:15:00Z',
  },
  {
    id: 'don-5',
    donor: { id: 'user-6', name: 'Sarah Johnson', email: 'sarah@example.com' },
    campaign: null,
    amount: 300,
    status: TRANSACTION_STATUS.COMPLETED,
    paymentGateway: 'CARD',
    transactionId: 'TXN-2024-005',
    createdAt: '2024-11-25T11:30:00Z',
  },
  {
    id: 'don-6',
    donor: { id: 'user-1', name: 'John Donor', email: 'john@example.com' },
    campaign: { id: 'camp-3', title: 'Build Schools Project' },
    amount: 2000,
    status: TRANSACTION_STATUS.FAILED,
    paymentGateway: 'CARD',
    transactionId: 'TXN-2024-006',
    createdAt: '2024-11-26T14:00:00Z',
  },
];

// =============================================================================
// MOCK REQUESTS
// =============================================================================

export const mockRequests = [
  {
    id: 'req-1',
    title: 'School Supplies for 100 Children',
    description: 'We need basic school supplies including notebooks, pens, and backpacks for underprivileged children in our community.',
    category: 'Education',
    urgency: URGENCY_LEVELS.HIGH,
    targetAmount: 5000,
    currentAmount: 3200,
    status: REQUEST_STATUS.PENDING,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    location: 'California, USA',
    createdAt: '2024-11-01T10:00:00Z',
    deadline: '2024-12-31T23:59:59Z',
    beneficiaryCount: 100,
  },
  {
    id: 'req-2',
    title: 'Emergency Medical Aid for Rural Clinic',
    description: 'Our rural clinic urgently needs medical supplies and equipment to serve the local community.',
    category: 'Healthcare',
    urgency: URGENCY_LEVELS.CRITICAL,
    targetAmount: 10000,
    currentAmount: 7500,
    status: REQUEST_STATUS.APPROVED,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    location: 'Rural Texas, USA',
    createdAt: '2024-11-10T08:00:00Z',
    deadline: '2024-12-20T23:59:59Z',
    beneficiaryCount: 500,
  },
  {
    id: 'req-3',
    title: 'Food Packages for Ramadan',
    description: 'Distribute food packages to 200 families during Ramadan.',
    category: 'Food',
    urgency: URGENCY_LEVELS.MEDIUM,
    targetAmount: 8000,
    currentAmount: 2000,
    status: REQUEST_STATUS.PENDING,
    createdBy: { id: 'user-5', name: 'New NGO Org' },
    location: 'Los Angeles, USA',
    createdAt: '2024-11-15T12:00:00Z',
    deadline: '2025-03-01T23:59:59Z',
    beneficiaryCount: 200,
  },
  {
    id: 'req-4',
    title: 'Winter Clothing Drive',
    description: 'Collect and distribute winter clothing to homeless individuals.',
    category: 'Shelter',
    urgency: URGENCY_LEVELS.HIGH,
    targetAmount: 3000,
    currentAmount: 3000,
    status: REQUEST_STATUS.FULFILLED,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    location: 'Chicago, USA',
    createdAt: '2024-10-01T10:00:00Z',
    deadline: '2024-12-01T23:59:59Z',
    beneficiaryCount: 150,
  },
];

// =============================================================================
// MOCK CAMPAIGNS
// =============================================================================

export const mockCampaigns = [
  {
    id: 'camp-1',
    title: 'Winter Relief Campaign 2024',
    description: 'Providing warm clothing and blankets to homeless individuals during winter. Join us in making a difference this cold season.',
    goalAmount: 25000,
    raisedAmount: 15600,
    status: CAMPAIGN_STATUS.ACTIVE,
    isEmergency: false,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    startDate: '2024-11-01T00:00:00Z',
    endDate: '2025-02-28T23:59:59Z',
    donorCount: 89,
    beneficiaryCount: 500,
  },
  {
    id: 'camp-2',
    title: 'Emergency Flood Relief',
    description: 'Urgent relief for families affected by recent floods. Providing food, shelter, and medical aid to those in need.',
    goalAmount: 50000,
    raisedAmount: 32000,
    status: CAMPAIGN_STATUS.ACTIVE,
    isEmergency: true,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    startDate: '2024-11-15T00:00:00Z',
    endDate: '2024-12-31T23:59:59Z',
    donorCount: 156,
    beneficiaryCount: 200,
  },
  {
    id: 'camp-3',
    title: 'Build Schools Project',
    description: 'Long-term campaign to build and equip 5 schools in underserved communities. Education changes lives.',
    goalAmount: 100000,
    raisedAmount: 45000,
    status: CAMPAIGN_STATUS.DRAFT,
    isEmergency: false,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    startDate: '2024-09-01T00:00:00Z',
    endDate: '2025-12-31T23:59:59Z',
    donorCount: 234,
    beneficiaryCount: 1000,
  },
  {
    id: 'camp-4',
    title: 'Clean Water Initiative',
    description: 'Building wells and water purification systems in rural areas.',
    goalAmount: 75000,
    raisedAmount: 75000,
    status: CAMPAIGN_STATUS.COMPLETED,
    isEmergency: false,
    createdBy: { id: 'user-2', name: 'Hope Foundation' },
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-10-31T23:59:59Z',
    donorCount: 412,
    beneficiaryCount: 2000,
  },
];

// =============================================================================
// MOCK ANALYTICS
// =============================================================================

export const mockAnalytics = {
  totalUsers: 1245,
  totalDonations: 145680,
  activeCampaigns: 24,
  pendingRequests: 18,
  monthlyDonations: [
    { month: 'Jan', amount: 12000 },
    { month: 'Feb', amount: 15000 },
    { month: 'Mar', amount: 18000 },
    { month: 'Apr', amount: 14000 },
    { month: 'May', amount: 16000 },
    { month: 'Jun', amount: 19000 },
    { month: 'Jul', amount: 22000 },
    { month: 'Aug', amount: 20000 },
    { month: 'Sep', amount: 24000 },
    { month: 'Oct', amount: 26000 },
    { month: 'Nov', amount: 28000 },
    { month: 'Dec', amount: 31680 },
  ],
  usersByRole: {
    DONOR: 892,
    VOLUNTEER: 234,
    NGO: 115,
    ADMIN: 4,
  },
  recentActivity: [
    { type: 'donation', description: 'John D. donated $500', time: '2 hours ago' },
    { type: 'campaign', description: 'New campaign created', time: '5 hours ago' },
    { type: 'verification', description: 'NGO verified', time: '1 day ago' },
    { type: 'request', description: 'New request submitted', time: '2 days ago' },
  ],
};

// =============================================================================
// EXPORTS
// =============================================================================

export default {
  mockUsers,
  mockDonations,
  mockRequests,
  mockCampaigns,
  mockAnalytics,
};
